
-- Table to store inquiries
CREATE TABLE inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Policy to allow anyone to insert inquiries (since we don't have auth users, just student names)
CREATE POLICY "Enable insert for all users" ON inquiries FOR INSERT WITH CHECK (true);

-- Policy to allow reading inquiries (optional, maybe only for admins or the user who created it if we had auth)
-- For now, let's allow reading so we can display them if needed, or just for debugging
CREATE POLICY "Enable read access for all users" ON inquiries FOR SELECT USING (true);
